---
name: Infrastructure

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "iac/**"
      - "!**test.go"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  skip-duplicate-actions:
    name: Skip Duplicate Actions
    runs-on: ubuntu-latest

    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cancel_others: true
          concurrent_skipping: never

  iac:
    name: Setup Infrastructure
    if: ${{ github.event_name == 'pull_request' || contains(github.event.head_commit.modified, 'iac/plm/**/*.go') || contains(github.event.head_commit.modified, 'iac/plm/util/**/.go') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Go latest
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Download dependencies
        run: |
          go get -u ./...
          go mod download
        working-directory: iac/kind

      - name: Pulumi login
        run: pulumi login --local
        env:
          PULUMI_SKIP_UPDATE_CHECK: "true"
          PULUMI_CONFIG_PASSPHRASE: ""
        working-directory: iac/kind

      - name: Run kind
        run: go run -v .
        working-directory: iac/kind
